### ISSUE TITLE
Quais serão as principais tags de notícias

### ISSUE THREAD

**Issue by ARTSTRET** [SamZuckerberg/WebNews#3]
Os principais assuntos da página tem que ter conexão com o tema (Geek).
Exemplo: games, cultura asiática, filmes...

**Comment by leonardonaoki** [comment]
As categorias podem ser: 
- Tecnologia 
- Jogos 
- Comics/HQ's 
- Livros 
- Filmes
- Animes/Mangás 
- Séries
